# Funding & Sponsorship for Willi-Mako Client SDK

# GitHub Sponsors (Recommended)
github: [energychain]

# Open Collective (Community-driven funding)
open_collective: willi-mako

# Corporate Sponsorship & Support
custom:
  - https://github.com/energychain/willi-mako-client/blob/main/docs/SPONSORSHIP.md
  - mailto:dev@stromdao.com

# Alternative Platforms
# patreon: willi-mako
# ko_fi: willi-mako
